version: "3.10"

services:

  worker:

    build: .

    environment:

       API_ID: $API_ID

       API_HASH: $API_HASH

       BOT_TOKEN: $BOT_TOKEN

       DURATION_LIMIT: $DURATION_LIMIT

       STRING_SESSION: $STRING_SESSION

       SUDO_USERS: $SUDO_USERS

       OWNER_ID: $OWNER_ID

       LOG_GROUP_ID: $LOG_GROUP_ID

       MONGODB_URL: $MONGODB_URL
       UPSTREAM_REPO: $UPSTREAM_REPO

       UPSTREAM_BRANCH: $UPSTREAM_BRANCH

       NETWORK: $NETWORK

       GROUP: $GROUP

       BOT_NAME: $BOT_NAME

       IMG_1: $IMG_1 

       IMG_2: $IMG_2 

       IMG_5: $IMG_5

       YOUTUBE_IMG_URL: $YOUTUBE_IMG_URL
